=== AlbertoLMSIG/LMSGI_UD4/Modulo_Cfgs/Moduloscfgs.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT modulos (modulo)+>
<!ELEMENT modulo (nombre,contenido+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT contenido (ud,tipo,descripcion)>
<!ELEMENT ud (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== AlbertoLMSIG/LMSGI_UD4/Modulos_CFGS/Moduloscfgs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modulos SYSTEM "Moduloscfgs.dtd">
<modulos>
    <modulo>
        <nombre>Lenguaje de Marca</nombre>
        <contenido>
            <ud> 3 </ud>
            <tipo>Almacenamiento de la informacion</tipo>
            <descripcion>Procesar la informacion</descripcion>
        </contenido>
        <contenido>
            <ud> 4 </ud>
            <tipo> XML</tipo>
            <descripcion>Uso de xml, dtd y xsd</descripcion>
        </contenido>
    </modulo>
    <modulo>
        <nombre>Base de datos</nombre>
        <contenido>
            <ud> 5 </ud>
            <tipo> MYSQL </tipo>
            <descripcion> Generar base de datos y administrala </descripcion>
        </contenido>
    </modulo>
    <modulo>
        <nombre>Programacion</nombre>
        <contenido>
            <ud> 4 </ud>
            <tipo> JAVA </tipo>
            <descripcion> Aprender con juegos </descripcion>
        </contenido>
    </modulo>
</modulos>
